---
output: 
    html_document:
        includes:
            in_header: assets/huskyheader.html
            before_body: assets/huskynavbar.html
            after_body: assets/huskyshoutouts.html
---

# Decomposing Geographic Changes in Mexico's Child Mortality

## Background  
In this analysis we unpack some of the interesting results from examining the change in under 5 mortality by examining$~_0q_5$, the probability of death before age 5, by municipality within Mexico. n 2015 at the end of the tracking period for the Millennium Development Goals (MDGs) the report Countdown to 2015, released by the World Health Organization, stated that, of the 75 priority countries followed by an ongoing analysis of child mortality monitoring, Mexico was one of twenty five countries that successfully achieved the goal of reducing under 5 mortality by two thirds, reducing their national under 5 mortality rate from 48 to 16 deaths per 1000 live births. Mexico's 2456 municipalities contain diverse set of populations and by examining how municipalities contributed to the change in national change level of child mortality, we can get a better understanding of how subpopulations differentially experience child mortality events and how this has changed over time.

## Data

De-identified person level data was extracted from INEGI and SINAC vital registration reports for the years 2000 to 2015 for birth records. Of the 43594696 birth records that were extracted 99.65% had a properly identified household location of parents that was used as the geolocation for this analysis, placing each record in one of the 2456 municipalities within Mexico. The records that did not have a municipality associated with them were approximately evenly distributed across states and were discarded from the analysis. Death registration data was extracted from person level de-identified INEGI reports where municipality of residence, year of occurrence, and age of individual given by single year was used provided that information existed for the death record. Of the 592274 deaths that were reported as under the age of 5, 99.72% had values for year, age, and municipality that were valid. Since data was not linked by person and single year populations by single year age and municipality were not available in other data sources, populations were estimated by taking the births of individuals for a particular municipality age and moving them one year forward in age as calendar year progressed, while also subtracting the deaths for that population. The formula is as follows where $P$ is the population number $D$ is the death number, $a$ is an age, $t$ is a single time period, and $l$ is a municipality.

$$
P_{l,a,t} = P_{l, a-1, t-1} - D_{l, a-1, t-1}
$$

This cohort method of tracking mortality and populations makes the assumption of net zero migration for all demographic units.

## Methods  

The model used to estimate age specific mortality follows the following form

$$
D_{l,a,t} \sim Poisson(\lambda_{l, a, t} \times P_{l,a,t}) \\
\lambda_{l, a, t} = exp(\beta_a + \phi_{l,a,t}) \\
\phi \sim MVN(0, Q) \\
Q = Q^t \otimes Q^a \otimes Q^l \\
Q^a \sim AR_1(\rho^a) \\
Q^t \sim AR_1(\rho^t) \\
Q^l \sim LCAR(\rho^l, \sigma)
$$

Where $\phi$ is a set of random effects that describe the latent age-spatiotemporal correlations that exist in the underlying mortality rates. These random effects have the effect of smoothing data such that outliers and improbably low or high observed rates of age specific mortality in a given year for a particular geography due to small sample size are adjusted base on the correlations observed in the dataset examined together. The model produces a set of parameters $\lambda_{l, a, t}$ which are age specific mortality rates for, for specific municipality-year which then can be converted to$~_0q_5$. The benefit to this approach is that it allows us to take into account the correlated structure of the mortality events that we observe as well as leverage the uncertainty in our estimates that are attributable to variable sample sizes observed across different municipalities and years.

In order to remain consistent with current demographic estimates of mortality, we raked our results such that they matched the GBD 2016 state level estimates of child mortality in Mexico.

## Results

Municipality  level results can be aggregated to both state and national levels in order to assess trend on more course geographic scales. The national level results in this analysis reflect the findings found in several other studies. Mexico has greatly reduced its level of child mortality as shown in the following graph with a significant decrease in the national level of$~_5q_0$.

```{R loads, echo=FALSE, warning=FALSE, message=FALSE}
pacman::p_load(INLA, TMB, raster, data.table, ggplot2, dplyr, dtplyr, ineq,
               INSP, surveillance, clusterPower, rvest, spdep, plotly, tidyr,
               stringr, leaflet, latex2exp)

setwd("~/Documents/MXU5MR/analysis/outputs/")
load("~/Documents/MXU5MR/analysis/outputs/uncertainty_draws.Rdata")
load("~/Documents/MXU5MR/IHMEanlaysis/adjust.Rdata")
load("~/Documents/MXU5MR/IHMEanlaysis/df_mxstate.RData")
U1state <- rename(U1state, YEAR=year)
U5state <- rename(U5state, YEAR=year)
DT <- fread("~/Documents/MXU5MR/analysis/outputs/model_phi_full.csv") %>%
    as.data.frame

DFName <- mx.sp.df@data %>%
    mutate(GEOID=as.numeric(GEOID)) %>%
    left_join(rename(df_mxstate, CVE_ENT=region)) %>%
    rename(Municipality=NOM_MUN, State=state_name_official) %>%
    select(GEOID, Municipality, State)

DFpop <- DT %>%
    filter(POPULATION != 0) %>%
    select(GEOID, YEAR, EDAD, POPULATION) %>%
    group_by(GEOID, EDAD) %>%
    summarize(Zpop=min(POPULATION)) %>%
    right_join(subset(DT, select=c(GEOID, EDAD, YEAR, POPULATION, DEATHS))) %>%
    mutate(POPULATION=ifelse(POPULATION == 0, Zpop, POPULATION)) %>%
    select(-Zpop) %>%
    ungroup %>%
    mutate(ENT_RESID=as.numeric(str_sub(sprintf("%05d", GEOID), 1, 2))) %>%
    mutate(RateAdj=apply(MRdraws, 1, mean)) %>%
    left_join(subset(U1state, select=c(ENT_RESID, YEAR, U1AdjPop))) %>%
    left_join(subset(U5state, select=c(ENT_RESID, YEAR, U5AdjPop))) %>%
    mutate(AdjPop=ifelse(EDAD==0, U1AdjPop, U5AdjPop)) %>%
    mutate(Population=POPULATION * AdjPop) %>%
    select(GEOID, EDAD, YEAR, Population, RateAdj) %>%
    mutate(RateAdjL=apply(MRdraws, 1, quantile, probs=.025)) %>%
    mutate(RateAdjH=apply(MRdraws, 1, quantile, probs=.975)) %>%
    as.data.frame

MEXlistw <- poly2nb(mx.sp.df, queen=TRUE) %>% nb2listw

tidymap <- fortify(mx.sp.df) %>% mutate(id=as.numeric(id)) %>%
    left_join(mx.sp.df@data %>% mutate(id=0:(nrow(mx.sp.df)-1)), by="id") %>%
    mutate(GEOID=as.numeric(GEOID))
```

```{R natLevel, echo=FALSE, warning=FALSE, message=FALSE}
Ddraws[,POPULATION:=DFpop$Population]
Ddraws[,GEOID:=DT$GEOID]

natdraws <- Ddraws[,lapply(.SD, sum), by=list(EDAD, YEAR)]
cols <- names(Ddraws)[grepl("sample", names(Ddraws))]
natdraws[ , (cols) := lapply(.SD, `/`, POPULATION), .SDcols = cols]
natdraws[,POPULATION:=NULL]
natdraws[,EDAD:=NULL]
natdraws <- natdraws[,lapply(.SD, function(x) 1-prod(1-x)), by=YEAR]
natdraws[,m_:=apply(as.matrix(subset(natdraws, select=cols)), 1, mean)]
natdraws[,l_:=apply(as.matrix(subset(natdraws, select=cols)), 1, quantile, probs=.025)]
natdraws[,h_:=apply(as.matrix(subset(natdraws, select=cols)), 1, quantile, probs=.975)]

pNat <- ggplot(natdraws, aes(x=YEAR, y=m_)) + geom_line() +
    geom_ribbon(aes(x=YEAR, ymin=l_, ymax=h_), alpha=.25) +
    labs(x="Year", y="5Q0", title="National Estimates of 5Q0") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic()

ggplotly(pNat)
```

With this analysis we have the ability to inspect the changes that occur across the municipalities in Mexico and weight them relative to their population contribution to the national average. By doing so we can estimate the entire distribution of how the population of Mexico experiences$~_5q_0$ across the country and how this distribution changes from year to year. The Density plot below shows how the distribution of$~_5q_0$ experienced across Mexico has changed from 2000 to to 2015. The mean of the two distributions correspond to the national level$~_5q_0$ plotted above for the years 2000 and 2015, however by viewing this distribution we can better understand how in a given year mortality various across municipalities. For example in addition to observing the declining mean that is shown in the time series plot we can see that from the year 2000 to 2015 the variance of the distribution has also decreased, resulting in a narrower range of mortality levels experienced in 2015.

```{R histochnage, echo=FALSE, warning=FALSE, message=FALSE}
DFhist <- DFpop %>%
    group_by(GEOID, YEAR) %>%
    summarize(Pop=round(sum(Population)/10)) %>%
    filter(YEAR %in% c(2000, 2015)) %>%
    left_join(DF5q0, by=c("GEOID", "YEAR")) %>%
    select(GEOID, YEAR, Pop, fqz)

hist2000 <- with(subset(DFhist, YEAR == 2000), rep(fqz, Pop))
hist2015 <- with(subset(DFhist, YEAR == 2015), rep(fqz, Pop))

cScale <- c(
    '#66c2a5','#fc8d62','#8da0cb','#e78ac3','#a6d854','#ffd92f','#e5c494'
)

phist <- data.frame(Value=c(hist2000, hist2015)) %>%
    mutate(Year=rep(c(2000, 2015), c(length(hist2000), length(hist2015)))) %>%
    mutate(Year=as.factor(Year)) %>%
    ggplot(aes(x=Value, group=Year, fill=Year)) +
    geom_density(alpha=.6, adjust=4, stat="density") +
    theme_classic() +
    xlim(c(0, .075)) +
    labs(y="Density", x="5q0",
         title="Mexico Population Distribution of 5q0") +
    scale_fill_manual(values = cScale)

phist
```

Another way to examine the decrease in the variation of child mortality across municipalities in Mexico is to assess changes in measures of inequality over time. For example we can take the .99 percentile of$~_5q_0$ and subtract from it the .01 percentile of$~_5q_0$ from a given year in order to get a measure of absolute inequality. Alternatively we may take the .99 percentile of$~_5q_0$ and divide it by the .01 percentile of$~_5q_0$ for any given year in order to get a measure of relative inequality. In addition, because our analysis not only computes the mean estimates of mortality rates but also computes uncertainty for child mortality rates, and also for$~_5q_0$, we can also calculate uncertainty related to ur estimates of absolute and relative inequality as well. Because we have a narrowing distribution of$~_5q_0$ in Mexico between the years 2000 and 2015 we see that both measures of absolute and relative inequality drop significantly between the two years.

```{R inequality, echo=FALSE, warning=FALSE, message=FALSE}
hivals <- apply(q0array, c(2,3), quantile, .99)
lovals <- apply(q0array, c(2,3), quantile, .01)
relineq <- hivals / lovals
absineq <- hivals - lovals
relineqdiff <- relineq[nrow(relineq),] - relineq[1,]
absineqdiff <- absineq[nrow(absineq),] - absineq[1,]
DTineq <- data.table(year=2000:2015, relineq=apply(relineq, 1, mean),
                     relineqlow=apply(relineq, 1, quantile, probs=.025),
                     relineqhi=apply(relineq, 1, quantile, probs=.975),
                     absineq=apply(absineq, 1, mean),
                     absineqlow=apply(absineq, 1, quantile, probs=.025),
                     absineqhi=apply(absineq, 1, quantile, probs=.975))

pineqR <- ggplot(DTineq, aes(x=year, y=relineq)) + geom_line() +
    geom_ribbon(aes(x=year, ymin=relineqlow, ymax=relineqhi), alpha=.25) +
    labs(x="Year", y="Relative Inequality", title="5Q0 Inequality") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic()

pineqA <- ggplot(DTineq, aes(x=year, y=absineq)) + geom_line() +
    geom_ribbon(aes(x=year, ymin=absineqlow, ymax=absineqhi), alpha=.25) +
    labs(x="Year", y="Absolute Inequality", title="5Q0 Inequality") +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme_classic()

ggplotly(pineqA)
ggplotly(pineqR)
```

For both the metrics of absolute and relative inequality we can see that there has been a stagnation in reduction between the years 2010 and 2015 despite the national values of$~_5q_0$ continuing to decline. Admittedly, our measure of inequality is not very robust to the entirety of the composition of the distribution for a given year, however, if we inspect the density of$~_5q_0$ for these two years we can see that despite having a shift of declining mortality we still observe a positive skew to the distribution with a left tail.

```{R histochnage2, echo=FALSE, warning=FALSE, message=FALSE}
DFhist2 <- DFpop %>%
    group_by(GEOID, YEAR) %>%
    summarize(Pop=round(sum(Population)/10)) %>%
    filter(YEAR %in% c(2010, 2015)) %>%
    left_join(DF5q0, by=c("GEOID", "YEAR")) %>%
    select(GEOID, YEAR, Pop, fqz)

hist2010 <- with(subset(DFhist2, YEAR == 2010), rep(fqz, Pop))
hist2015 <- with(subset(DFhist2, YEAR == 2015), rep(fqz, Pop))

phist2 <- data.frame(Value=c(hist2010, hist2015)) %>%
    mutate(Year=rep(c(2010, 2015), c(length(hist2010), length(hist2015)))) %>%
    mutate(Year=as.factor(Year)) %>%
    ggplot(aes(x=Value, group=Year, fill=Year)) +
    geom_density(alpha=.6, adjust=4, stat="density") +
    theme_classic() +
    xlim(c(0, .075)) +
    labs(y="Density", x="5q0",
         title="Mexico Population Distribution of 5q0") +
    scale_fill_manual(values = rev(cScale[2:3]))

phist2
```

This stabilization of levels inequality does not necessarily mean that there exists a problem with the health outcome distribution within Mexico or that systematic inequalities exist. If the the level of$~_5q_0$ were randomly distributed across geographies and time, that is if there was no correlation between a municipalities level of$~_5q_0$ and its previous levels of$~_5q_0$ or its neighbors levels of$~_5q_0$, then the variation that we observe in a given year could be attributable to random chance. This is not the case, however, in Mexico and an examination of the level of$~_5q_0$ using a choropleth map shows us that there is at least some degree of spatial autocorrelation that results in higher than average municipality level values of$~_5q_0$ in the states of Chihuahua, Guerrero, Chiapas, and Oaxaca. Though outside the scope of this analysis the underlying factors that contribute to and define these geographic disparities in $~_5q_0$, such access to health facilities, indigenous status of the population, socioeconomic and educational factors have been explored within the context with Mexico and should be further analyzed in relation to small area changes in Mexico's child mortality demographics.

```{R nat2015map, echo=FALSE, warning=FALSE, message=FALSE}
df <- mx.sp.df
df@data$GEOID <- as.numeric(df@data$GEOID)
col <- "fqz"
df@data <- left_join(df@data, subset(DF5q0, YEAR == 2015)) %>%
    left_join(DFpop %>%
    group_by(GEOID, YEAR) %>%
    summarize(Pop=round(sum(Population)))) %>%
    left_join(DFName)
df@data$data <- df@data[, col]
lab_label <- ifelse(is.null(label), col, label)
popup <- paste0(
    "State: ", df@data$State,
    "<br>Municipality: ", df@data$NOM_MUN,
    "<br>5q0: ", round(df@data$data, 4), "(",
    round(df$fqzl, 4), ", ",
    round(df$fqzh, 4), ")<br>",
    "Population: ", df$Pop)
pal <- colorNumeric(palette = "Spectral", domain = df@data$data,
                    reverse=TRUE)
map1 <- leaflet() %>% addProviderTiles("CartoDB.Positron") %>%
    addPolygons(data = df, fillColor = ~pal(data), color = "#b2aeae",
        weight = 0.3, fillOpacity = 0.7, smoothFactor = 0.2,
        popup = popup) %>% addLegend("bottomleft", pal = pal,
    values = df$data, title ="Mexico 5q0(2015)", opacity = 1)

corReal <- q0array[,c(1,16),] %>%
    apply(3, function(x) cor(x[,1], x[,2])) %>%
    quantile(probs=c(.025, .5, .975)) %>%
    round(4)

map1
```

In addition to the geographic correlations observed in the data we also see correlation in time of the measures of$~_5q_0$ for municipalities. The plot below shows the correlation between the mean estimates of$~_5q_0$ in Mexico between the years 2000 and 2015. The dotted line is the one to one line such that points which fall below the line had a positive net decrease between the two years. Its evident that most municipalities had a net positive change and that the distribution has become much narrower between the two years, as we have shown above as well. What we can more easily see in this view is that there still exists a positive correlation between the two years `r corReal[[2]]` (`r corReal[[1]]`-`r corReal[[3]]`), indicating that there remains to some degree a consistent placing of municipalities on the distribution of$~_5q_0$ across years.

```{R natTimeCor, echo=FALSE, warning=FALSE, message=FALSE}
DFCompDelta <- DFpop %>% as.data.frame %>%
    group_by(GEOID, YEAR) %>%
    summarize(Population=sum(Population)) %>%
    filter(YEAR %in% c(2000, 2015)) %>%
    left_join(as.data.frame(DF5q0), by=c("GEOID", "YEAR")) %>%
    select(-fqzl, -fqzh) %>%
    gather(variable, value, -(GEOID:YEAR)) %>%
    unite(temp, variable, YEAR) %>%
    spread(temp, value) %>%
    ungroup %>%
    mutate(Population_2000=Population_2000/sum(Population_2000)) %>%
    mutate(Population_2015=Population_2015/sum(Population_2015)) %>%
    mutate(grossI=(fqz_2015+fqz_2000)*.5*(Population_2015-Population_2000)) %>%
    mutate(residI=(Population_2015+Population_2000)*.5*(fqz_2015-fqz_2000)) %>%
    mutate(totI=grossI + residI) %>%
    arrange(totI/Population_2015) %>%
    left_join(subset(DFName, select=c(GEOID, State, Municipality)))

rChange <- (sum(DFCompDelta$residI)/
    (sum(DFCompDelta$residI) + sum(DFCompDelta$grossI))) %>%
    round(4) %>% `*`(100)

pal2 <- colorNumeric(palette = "Spectral", domain = 1:32,
                    reverse=TRUE)

pTimeCor <- DFCompDelta %>%
    ggplot(aes(x=fqz_2000, y=fqz_2015, color=State,
               text=paste0("Municipality: ", Municipality))) +
    geom_point() +
    scale_color_manual(values = pal2(1:32), guide=F) +
    theme_classic() +
    xlab("2000 5q0") + ylab("2015 5q0") +
    ggtitle("Mexico Municipalities Change in 5q0") +
    lims(x=c(0, .125), y=c(0, .125)) +
    geom_abline(linetype=2)

ggplotly(pTimeCor)
```

Another view that we may take in order to inspect how Mexico has decreased its under five mortality rate and$~_5q_0$ is to decompose the changes contributed by each municipality as a function as its changing population contribution to the national average and the change in its estimated value of$~_5q_0$. Take for example an entity $\delta$ which is measured at two time points, $\delta_{2000}$ and $\delta_{2015}$ delta is composed of two sub units $A$ and $B$ which are also measured at the same two time points. Let us say that in 2000 that the rate for $A_{2000}$ is $.2$ and the rate for $B_{2000}$ is $.8$ and each subunit constitutes .5 of the total population $\delta_{2000}$. It is easy to see that the rate for $\delta_{2000}$ is then $.5$. If we have a situation where the $\delta_{2015}$ value is now $.26$ this could have been achieved in very different ways. One scenario is where the rates for $A$ and $B$ remain constant but there population contribution changed to $.9$ and $.1$ respectively. In this scenario no rates decreased and yet the aggregate rate decreased because of a change in the population composition. On the other hand you can have the entire change be driven by changes in the rates of the subcomponents. In that scenario $A$ and $B$ maintain the same population contribution over time, $.5$ each, however the rates decrease. Theres is an infinite amount of scenarios where the total change is driven in part by changing rates of subcomponents and changing population composition. Kitagawa offers a method to do this decomposition using change over time for many entities, municipalities in our case, as unit of a larger entity and give the relative contribution made by each municipality. Using this method we find that nearly all of the decrease in Mexico's$~_5q_0$ comes from declining values of$~_5q_0$, `r rChange`%, within each municipality rather than changes in the population composition. With this method we can examine how X percentage of the population contributed to Y percentage of the overall change in$~_5q_0$. The graph below shows how a relatively small portion contributed to a majority of the change in$~_5q_0$, 22% of the population made up about 51% of the overall net positive decrease in$~_5q_0$ in Mexico between 2000 and 2015.

```{R deltaDecomp, echo=FALSE, warning=FALSE, message=FALSE}
pDecomp <- with(DFCompDelta,
     data.frame(Population=cumsum(Population_2015),
                Contribution=cumsum(totI) /sum(totI))) %>%
    ggplot(aes(x=Population, y=Contribution)) +
    geom_line() +
    geom_abline(linetype=2) +
    theme_classic()

mark <- quantile(DFCompDelta$fqz_2015, probs=.04)

influential2015 <- DFCompDelta %>%
    arrange(-Population_2015) %>%
    filter(row_number() %in% 1:100) %>%
    filter(fqz_2015 > mark) %>%
    mutate(Dratio=mark/fqz_2015)

DdrawsHyp <- filter(Ddraws, YEAR==2015) %>%
    as.data.frame() %>%
    left_join(subset(influential2015, select=c(GEOID, Dratio))) %>%
    mutate(Dratio=ifelse(is.na(Dratio), 1, Dratio)) %>%
    as.data.table()
cols <- names(DdrawsHyp)[grepl("sample", names(DdrawsHyp))]
DdrawsHyp[ , (cols) := lapply(.SD, `*`, Dratio), .SDcols = cols]
natdrawsHyp <- DdrawsHyp[,lapply(.SD, sum), by=list(EDAD, YEAR)]

natdrawsHyp[ , (cols) := lapply(.SD, `/`, POPULATION), .SDcols = cols]
natdrawsHyp[,POPULATION:=NULL]
natdrawsHyp[,GEOID:=NULL]
natdrawsHyp[,EDAD:=NULL]
natdrawsHyp[,Dratio:=NULL]
natdrawsHyp <- natdrawsHyp[,lapply(.SD, function(x) 1-prod(1-x)), by=YEAR]
natdrawsHyp[,m_:=apply(as.matrix(subset(natdrawsHyp, select=cols)), 1, mean)]
natdrawsHyp[,l_:=apply(as.matrix(subset(natdrawsHyp, select=cols)), 1, quantile, probs=.025)]
natdrawsHyp[,h_:=apply(as.matrix(subset(natdrawsHyp, select=cols)), 1, quantile, probs=.975)]


UrbPopP <- sum(influential2015$Population_2015)
UrbMP <- nrow(influential2015)/nrow(DFCompDelta)
UrbChange <- (quantile(1 - as.matrix(natdrawsHyp)[1, 2:1001]/
                          as.matrix(natdraws)[16, 2:1001],
         probs=c(.025, .5, .975)) * 100)  %>% round(2)


mark <- .01447
influential2015 <- DFCompDelta %>%
    mutate(Dratio=mark/fqz_2015) %>%
    filter(fqz_2015 > (mark*1.1))

DdrawsHyp <- filter(Ddraws, YEAR==2015) %>%
    as.data.frame() %>%
    left_join(subset(influential2015, select=c(GEOID, Dratio))) %>%
    mutate(Dratio=ifelse(is.na(Dratio), 1, Dratio)) %>%
    as.data.table()
cols <- names(DdrawsHyp)[grepl("sample", names(DdrawsHyp))]
DdrawsHyp[ , (cols) := lapply(.SD, `*`, Dratio), .SDcols = cols]
natdrawsHyp <- DdrawsHyp[,lapply(.SD, sum), by=list(EDAD, YEAR)]

natdrawsHyp[ , (cols) := lapply(.SD, `/`, POPULATION), .SDcols = cols]
natdrawsHyp[,POPULATION:=NULL]
natdrawsHyp[,GEOID:=NULL]
natdrawsHyp[,EDAD:=NULL]
natdrawsHyp[,Dratio:=NULL]
natdrawsHyp <- natdrawsHyp[,lapply(.SD, function(x) 1-prod(1-x)), by=YEAR]
natdrawsHyp[,m_:=apply(as.matrix(subset(natdrawsHyp, select=cols)), 1, mean)]
natdrawsHyp[,l_:=apply(as.matrix(subset(natdrawsHyp, select=cols)), 1, quantile, probs=.025)]
natdrawsHyp[,h_:=apply(as.matrix(subset(natdrawsHyp, select=cols)), 1, quantile, probs=.975)]

smallPopP <- sum(influential2015$Population_2015)
smallMP <- nrow(influential2015)/nrow(DFCompDelta)

smallChange <- (quantile(1 - as.matrix(natdrawsHyp)[1, 2:1001]/
                          as.matrix(natdraws)[16, 2:1001],
         probs=c(.025, .5, .975)) * 100) %>% round(2)

hi50MP <- DFCompDelta %>%
    mutate(PopTot=Population_2015) %>%
    arrange(-PopTot) %>%
    mutate(Population=cumsum(PopTot)) %>%
    filter(Population < .5) %>%
    nrow() %>%
    `/`(nrow(DFCompDelta))

hi50C <- DFCompDelta %>%
    mutate(PopTot=Population_2015) %>%
    arrange(-PopTot) %>%
    mutate(Population=cumsum(PopTot)) %>%
    filter(Population < .5) %>%
    nrow()

lo50C <- DFCompDelta %>%
    mutate(PopTot=Population_2015) %>%
    arrange(-PopTot) %>%
    mutate(Population=cumsum(PopTot)) %>%
    filter(Population >= .5) %>%
    nrow()

hi50 <- DFCompDelta %>%
    mutate(PopTot=Population_2015) %>%
    arrange(-PopTot) %>%
    mutate(Population=cumsum(PopTot)) %>%
    filter(Population < .5) %>%
    select(residI) %>%
    unlist %>%
    sum %>%
    `/`(sum(DFCompDelta$residI))

lo50MP <- DFCompDelta %>%
    mutate(PopTot=Population_2015) %>%
    arrange(-PopTot) %>%
    mutate(Population=cumsum(PopTot)) %>%
    filter(Population >= .5) %>%
    nrow() %>%
    `/`(nrow(DFCompDelta))

lo50 <- DFCompDelta %>%
    mutate(PopTot=Population_2015) %>%
    arrange(-PopTot) %>%
    mutate(Population=cumsum(PopTot)) %>%
    filter(Population >= .5) %>%
    select(residI) %>%
    unlist %>%
    sum %>%
    `/`(sum(DFCompDelta$residI))

ggplotly(pDecomp)
```

The graph above organizes the population such that ratio of contribution to national level change of$~_5q_0$ over population percentage of national total is ordered from least to greatest so that the area between the curve and the dotted line is also maximized. We can view the same plot with a different ordering to observe another phenomena. Suppose we are interested in looking at the contribution to national level change of$~_5q_0$ comparing the largest municipalities such that about 50 percent of the national population is represented vs the smallest municipalities that make up the remaining 50% of the population. We would want to look at this result to see if there is a bias to where health is improving in comparing densely populated municipalities vs sparsely populated ones. 50% of Mexico's 2015 Under 5 population live in the largest `r round(hi50MP, 4)*100` of municipalities, living in `r hi50C` of the 2456 municipalities that make up Mexico. This population contributed to `r round(hi50, 4) * 100`% of the total reduction of national$~_5q_0$ while the 50% of the population living in the smallest `r lo50C` municipalities contributed to `r round(lo50, 4) * 100`% of the national change. Below is the same graph but this time ordered by smallest municipality to largest municipality so that you can see how the smallest x% of the population contributed to y% of the over all change in national$~_5q_0$.


```{R deltaDecompPop, echo=FALSE, warning=FALSE, message=FALSE}

pPopDecomp <- DFCompDelta %>%
    arrange(Population_2015) %>%
     mutate(Population=cumsum(Population_2015),
            Contribution=cumsum(residI /sum(residI))) %>%
    ggplot(aes(x=Population, y=Contribution)) +
    geom_line() +
    geom_abline(linetype=2) +
    theme_classic()

ggplotly(pPopDecomp)
```

This view is important to understand the changes occurring to differently constructed populations, such as urban(dense high population) vs rural(sparse low population). For example, looking at future scenarios of further reduction of under 5 mortality and$~_5q_0$, if the largest 100 municipalities, representing `r round(UrbPopP,4)*100`% of the population, reduced their$~_5q_0$ to the level of the 4th percentile of all the 2015 municipality mean level estimates of $~_5q_0$ we would see a reduction of national level mortality of `r UrbChange[[2]]`(`r UrbChange[[1]]`- `r UrbChange[[3]]`). On the other hand if we were able to reduce the mortality of all municipalities that were over 1.1 times the national average of$~_5q_0$,`r round(smallMP*2456)` municipalities representing `r round(smallPopP,4)*100`% of the population, to the national average we would see a similar level of reduction `r smallChange[[2]]`(`r smallChange[[1]]`- `r smallChange[[3]]`).

We can examine each individual entity separately in order to see how its contribution to national level$~_5q_0$has evolved over time. A look at the two sides of the spectrum show use the temporal trend of the five most influential positive changes and negative changes. It is interesting to note that that both of these groups show net decreases over time however the second plot shows us that the negative contribution group is increasing in its child population size thus contributing more to the national average.

```{R TSContrib, echo=FALSE, warning=FALSE, message=FALSE}
pContra <- DFCompDelta %>%
    arrange(totI) %>%
    filter(row_number() %in% 1:5 | row_number() %in% (n()-4):(n())) %>%
    mutate(Contribution=c(rep(c("Strong +", "Weak -"), each=5))) %>%
    select(GEOID, Contribution) %>%
    left_join(DF5q0, by="GEOID") %>%
    left_join(summarize(group_by(DFpop, GEOID, YEAR), Pop=sum(Population))) %>%
    left_join(DFName) %>%
    ggplot(aes(x=YEAR, y=fqz, ymin=fqzl, ymax=fqzh, group=GEOID,
               color=Contribution, fill=Contribution,
               text=paste("State: ", State, "\n",
                          "Municiplaity: ", Municipality, "\n",
                          "Population: ", Pop, "\n",
                          "FQZ: ", fqz, "\n",
                          "Year: ", YEAR))) +
    geom_line() + geom_ribbon(alpha=.2, linetype=2) +
    theme_classic() +
    scale_fill_manual(values = cScale) +
    scale_color_manual(values = cScale) +
    labs(x="Year", y="5q0")

ggplotly(pContra, tooltip="text")
```

```{R pContraPop, message=FALSE, warning=FALSE, echo=FALSE}
pContraPop <- DFCompDelta %>%
    arrange(totI) %>%
    filter(row_number() %in% 1:5 | row_number() %in% (n()-4):(n())) %>%
    mutate(Contribution=c(rep(c("Strong +", "Weak -"), each=5))) %>%
    select(GEOID, Contribution) %>%
    left_join(DF5q0, by="GEOID") %>%
    left_join(summarize(group_by(DFpop, GEOID, YEAR), Pop=sum(Population))) %>%
    left_join(DFName) %>%
    ggplot(aes(x=YEAR, y=Pop, group=GEOID,
               color=Contribution,
               text=paste("State: ", State, "\n",
                          "Municiplaity: ", Municipality, "\n",
                          "Population: ", Pop, "\n",
                          "Year: ", YEAR))) +
    geom_line() +
    theme_classic() +
    scale_color_manual(values = cScale) +
    labs(x="Year", y="Population")

ggplotly(pContraPop, tooltip="text")
```

If we decide to look at instead at the largest contributions from municipalities given by a change in rate we see population thats that have net increases and decreases of$~_5q_0$ that mirror its net negative and positive contribution to the decrease in national level$~_5q_0$. Note that even though large decreases in$~_5q_0$ were made in the first group 4 of the 5 municipalities with the largest net change due to rate reductions are still above the national average for$~_5q_0$.

```{R TSDelta, echo=FALSE, warning=FALSE, message=FALSE}
pDelta <- DFCompDelta %>%
    arrange(residI) %>%
    filter(row_number() %in% 1:5 | row_number() %in% (n()-4):(n())) %>%
    mutate(Delta=c(rep(c("Large Decrease", "Small Increase"), each=5))) %>%
    select(GEOID, Delta) %>%
    left_join(DF5q0, by="GEOID") %>%
    left_join(summarize(group_by(DFpop, GEOID, YEAR), Pop=sum(Population))) %>%
    left_join(DFName) %>%
    ggplot(aes(x=YEAR, y=fqz, ymin=fqzl, ymax=fqzh, group=GEOID,
               color=Delta, fill=Delta,
               text=paste("State: ", State, "\n",
                          "Municiplaity: ", Municipality, "\n",
                          "Population: ", Pop, "\n",
                          "FQZ: ", fqz, "\n",
                          "Year: ", YEAR))) +
    geom_line() + geom_ribbon(alpha=.2, linetype=2) +
    theme_classic() +
    scale_fill_manual(values = cScale) +
    scale_color_manual(values = cScale) +
    labs(x="Year", y="5q0")

ggplotly(pDelta, tooltip="text")
```

We can also focus are view on the bottom and top 5 municipalities ranked by their levels of$~_5q_0$ in 2015, regardless of their contribution to national$~_5q_0$. By hovering over the lines we can see that the relative under 5 population size of these municipalities is lower than they other municipalities that we have viewed which contribute more heavily to the national average. You can also see that that the state of Oaxaca, the state with the most municipalities in Mexico, has representation in both the top 5 lowest and highest performing municipality level$~_5q_0$ in Mexico as of 2015. Below the time series is a map of just Oaxaca's$~_5q_0$ estimates. If you wish to view a full set of results, time series plots and maps for all years at national, state and municipality levels, they may be viewed at the following link.

https://nmmarquez.twilightparadox.com/u5mr_results/

```{R TSHiLo, echo=FALSE, warning=FALSE, message=FALSE}
pHiLo <- DFCompDelta %>%
    arrange(fqz_2015) %>%
    filter(row_number() %in% 1:5 | row_number() %in% (n()-4):(n())) %>%
    mutate(Standing=c(rep(c("Top 5", "Bottom 5"), each=5))) %>%
    select(GEOID, Standing) %>%
    left_join(DF5q0, by="GEOID") %>%
    left_join(summarize(group_by(DFpop, GEOID, YEAR), Pop=sum(Population))) %>%
    left_join(DFName) %>%
    ggplot(aes(x=YEAR, y=fqz, ymin=fqzl, ymax=fqzh, group=GEOID,
               color=Standing, fill=Standing,
               text=paste("State: ", State, "\n",
                          "Municiplaity: ", Municipality, "\n",
                          "Population: ", Pop, "\n",
                          "FQZ: ", fqz, "\n",
                          "Year: ", YEAR))) +
    geom_line() + geom_ribbon(alpha=.2, linetype=2) +
    theme_classic() +
    scale_fill_manual(values = cScale) +
    scale_color_manual(values = cScale) +
    labs(x="Year", y="5q0")

ggplotly(pHiLo, tooltip="text")
```

## Oaxaca Map

```{R oax2015map, echo=FALSE, warning=FALSE, message=FALSE}
dfoax <- mx.sp.df
dfoax@data$GEOID <- as.numeric(dfoax@data$GEOID)
col <- "fqz"
dfoax@data <- left_join(dfoax@data, subset(DF5q0, YEAR == 2015)) %>%
    left_join(DFpop %>%
    group_by(GEOID, YEAR) %>%
    summarize(Pop=round(sum(Population)))) %>%
    left_join(DFName)
dfoax@data$data <- dfoax@data[, col]

dfoax <- dfoax[dfoax$State == "Oaxaca",]

popupoax <- paste0(
    "State: ", dfoax@data$State,
    "<br>Municipality: ", dfoax@data$NOM_MUN,
    "<br>5q0: ", round(dfoax@data$data, 4), "(",
    round(dfoax$fqzl, 4), ", ",
    round(dfoax$fqzh, 4), ")<br>",
    "Population: ", dfoax$Pop)
paloax <- colorNumeric(palette = "Spectral", domain = dfoax@data$data,
                    reverse=TRUE)
mapOax <- leaflet() %>% addProviderTiles("CartoDB.Positron") %>%
    addPolygons(data = dfoax, fillColor = ~paloax(data), color = "#b2aeae",
        weight = 0.3, fillOpacity = 0.7, smoothFactor = 0.2,
        popup = popupoax) %>%
    addLegend("bottomleft", pal = paloax,
    values = dfoax$data, title ="Oaxaca 5q0(2015)", opacity = 1)

mapOax
```

## Associations